---
title: "simulate the scariest thing"
author: "Shirley"
date: "10/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(simmer)
s<-purrr::map_df(1:500, ~{
  
  customer <- trajectory("customer") %>% 
    set_attribute("start_time", function() {now(haunted_house)}) %>% 
    seize("spot1") %>% 
    timeout(function() {rnorm(1,3,0.5)}) %>% 
    release("spot1") %>% 
    seize("spot2") %>% 
    timeout(function() {rnorm(1,3,0.5)}) %>% 
    release("spot2") %>% 
    branch(function() {sample(1:2,1, prob = c(0.5,0.5)) }, 
           continue = c(TRUE,TRUE),
           trajectory() %>% 
             seize("spot3_1") %>% 
             timeout(function() {rnorm(1,5,1)}) %>% 
             release("spot3_1"),
            trajectory() %>% 
             seize("spot3_2") %>% 
             timeout(function() {rnorm(1,5,1)}) %>% 
             release("spot3_2")|>
    seize("final_spot") |>
    timeout(function() {runif(n = 1, min = 5, max = 15)}) |>
    release("final_spot")
    )
  
  haunted_house <- simmer("haunted_house") %>% 
    add_resource("spot1", capacity = 8, queue_size = Inf) %>% 
    add_resource("spot2", capacity = 10, queue_size = Inf) %>%
    add_resource("spot3_1", capacity = 15, queue_size = Inf) %>%
    add_resource("spot3_2", capacity = 15, queue_size = Inf) %>%
    add_resource("final_spot", capacity = 15, queue_size = Inf) %>%
    add_generator("customer", customer,function() {c(0,rexp(n=500,rate = 2),-1)})
  
 simmer:: run(haunted_house, 480)
  s <- get_mon_arrivals(haunted_house)

  s$run<- .x
  
  s
})

s$wait_time<-s$end_time-s$start_time-s$activity_time

 library(ggplot2)
ggplot(s, aes(x = wait_time)) + # You will likely need to switch names here
  geom_histogram(bins = 10)

mean(s$activity_time)

```

